language: bash

os: linux
sudo: required
dist: trusty

env:
    - HTT_VERSION=master
    - HTT_VERSION=Release_2014.09.31
    - HTT_VERSION=Release_2016.03.11_Alpha

install:
    - sudo apt-get update
    - DEBIAN_FRONTEND=noninteractive sudo apt-get --yes --force-yes upgrade

script:
    - sudo bash DLNA_HTML5_Test_Tool_Installer.sh -r $HTT_VERSION

