language: bash

sudo: required

services:
  - docker

env:
    - HTT_OS_VERSION=14.04
      HTT_VERSIONS="Release_2014.09.31"
    - HTT_OS_VERSION=14.04
      HTT_VERSIONS="Release_2014.09.31 Release_2016.03.11_Alpha"
    - HTT_OS_VERSION=14.04
      HTT_VERSIONS="Release_2014.09.31 master"
    - HTT_OS_VERSION=14.04
      HTT_VERSIONS="Release_2014.09.31 Release_2016.03.11_Alpha master"
    - HTT_OS_VERSION=14.04
      HTT_VERSIONS="Release_2016.03.11_Alpha"
    - HTT_OS_VERSION=14.04
      HTT_VERSIONS="Release_2016.03.11_Alpha master"
    - HTT_OS_VERSION=14.04
      HTT_VERSIONS="master"
    - HTT_OS_VERSION=16.04
      HTT_VERSIONS="Release_2014.09.31"
    - HTT_OS_VERSION=16.04
      HTT_VERSIONS="Release_2014.09.31 Release_2016.03.11_Alpha"
    - HTT_OS_VERSION=16.04
      HTT_VERSIONS="Release_2014.09.31 master"
    - HTT_OS_VERSION=16.04
      HTT_VERSIONS="Release_2014.09.31 Release_2016.03.11_Alpha master"
    - HTT_OS_VERSION=16.04
      HTT_VERSIONS="Release_2016.03.11_Alpha"
    - HTT_OS_VERSION=16.04
      HTT_VERSIONS="Release_2016.03.11_Alpha master"
    - HTT_OS_VERSION=16.04
      HTT_VERSIONS="master"

install:
    - docker pull ubuntu:14.04
    - docker pull ubuntu:16.04
    - wget https://github.com/jpetazzo/pipework/raw/master/pipework
    - chmod +x pipework
    - sudo mv pipework /usr/local/bin

before_script:
    - echo nameserver 127.0.0.1 > resolv.conf
    - echo nameserver 8.8.8.8 >> resolv.conf
    - echo nameserver 8.8.4.4 >> resolv.conf

script:
    - INSTALL=$(docker run -dit ubuntu:${HTT_OS_VERSION} /bin/bash)
    - sudo pipework br0 ${INSTALL} 192.168.0.1/24
    - docker cp DLNA_HTML5_Test_Tool_Installer.sh ${INSTALL}:/root/DLNA_HTML5_Test_Tool_Installer.sh
    - docker cp resolv.conf ${INSTALL}:/etc/resolv.conf
    - for HTT_VERSION in ${HTT_VERSIONS}; do 
        docker exec ${INSTALL} bash /root/DLNA_HTML5_Test_Tool_Installer.sh --disable-network -y -r ${HTT_VERSION} || exit $?; 
      done
    - TEST=$(docker run -dit ubuntu:16.04 /bin/bash)
    - docker exec ${TEST} apt-get -y update
    - docker exec ${TEST} apt-get -y install dhclient host net-tools curl
    - sudo bash pipework br0 -i eth1 ${TEST} dhclient
    - docker cp Validate_Install.sh ${TEST}:/root/Validate_Install.sh
    - docker exec ${TEST} bash /root/Validate_Install.sh
