language: bash

sudo: required

services:
  - docker

env:
    - HTT_OS_VERSION=14.04
      HTT_VERSIONS="Release_2014.09.31"
    - HTT_OS_VERSION=14.04
      HTT_VERSIONS="Release_2014.09.31 Release_2016.03.11_Alpha"
    - HTT_OS_VERSION=14.04
      HTT_VERSIONS="Release_2014.09.31 master"
    - HTT_OS_VERSION=14.04
      HTT_VERSIONS="Release_2014.09.31 Release_2016.03.11_Alpha master"
    - HTT_OS_VERSION=14.04
      HTT_VERSIONS="Release_2016.03.11_Alpha"
    - HTT_OS_VERSION=14.04
      HTT_VERSIONS="Release_2016.03.11_Alpha master"
    - HTT_OS_VERSION=14.04
      HTT_VERSIONS="master"
    - HTT_OS_VERSION=16.04
      HTT_VERSIONS="Release_2014.09.31"
    - HTT_OS_VERSION=16.04
      HTT_VERSIONS="Release_2014.09.31 Release_2016.03.11_Alpha"
    - HTT_OS_VERSION=16.04
      HTT_VERSIONS="Release_2014.09.31 master"
    - HTT_OS_VERSION=16.04
      HTT_VERSIONS="Release_2014.09.31 Release_2016.03.11_Alpha master"
    - HTT_OS_VERSION=16.04
      HTT_VERSIONS="Release_2016.03.11_Alpha"
    - HTT_OS_VERSION=16.04
      HTT_VERSIONS="Release_2016.03.11_Alpha master"
    - HTT_OS_VERSION=16.04
      HTT_VERSIONS="master"

install:
    - docker pull ubuntu:14.04
    - docker pull ubuntu:16.04
    - wget https://github.com/jpetazzo/pipework/raw/master/pipework
    - chmod +x pipework
    - sudo mv pipework /usr/local/bin

script:
    - CONTAINER=$(docker run -dit ubuntu:${HTT_OS_VERSION} /bin/bash)
    - sudo pipework br0 ${CONTAINER} 192.168.0.1/24
    - docker cp DLNA_HTML5_Test_Tool_Installer.sh ${CONTAINER}:/root/DLNA_HTML5_Test_Tool_Installer.sh
    - for HTT_VERSION in ${HTT_VERSIONS}; do 
        docker exec ${CONTAINER} bash /root/DLNA_HTML5_Test_Tool_Installer.sh --disable-network -y -r ${HTT_VERSION} || exit $?; 
      done
